import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ur" | "hi";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.courses": "Courses",
    "nav.faculty": "Faculty",
    "nav.donation": "Donation",
    "nav.contact": "Contact",
    // Hero
    "hero.welcome": "Welcome to Al-Noor Madarsa",
    "hero.subtitle": "Providing Quality Islamic and Moral Education",
    "hero.apply": "Apply Now",
    "hero.donate": "Donate Now",
    // About Preview
    "about.preview.title": "About Our Madarsa",
    "about.preview.text": "Al-Noor Madarsa has been a beacon of Islamic education for over two decades, nurturing young minds with the light of Quran and Sunnah. Our dedicated faculty ensures every student receives personalized attention.",
    "about.preview.readmore": "Read More",
    // Courses Preview
    "courses.title": "Our Courses",
    "courses.subtitle": "Comprehensive Islamic Education Programs",
    "course.hifz.name": "Hifz-ul-Quran",
    "course.hifz.desc": "Complete memorization of the Holy Quran with proper Tajweed rules and pronunciation.",
    "course.hifz.duration": "Duration: 2-3 Years",
    "course.nazra.name": "Nazra Quran",
    "course.nazra.desc": "Learning to read the Holy Quran fluently with correct pronunciation and basic Tajweed.",
    "course.nazra.duration": "Duration: 6-12 Months",
    "course.alim.name": "Alim Course",
    "course.alim.desc": "Comprehensive Islamic scholarship covering Tafseer, Hadith, Fiqh, and Arabic language.",
    "course.alim.duration": "Duration: 6-8 Years",
    // Faculty
    "faculty.title": "Our Faculty",
    "faculty.subtitle": "Experienced and Dedicated Teachers",
    "faculty.teacher1.name": "Maulana Ahmad",
    "faculty.teacher1.title": "Head of Hifz Department",
    "faculty.teacher1.qual": "Alim | 15+ Years Experience",
    "faculty.teacher2.name": "Mufti Abdullah",
    "faculty.teacher2.title": "Senior Islamic Scholar",
    "faculty.teacher2.qual": "Mufti | 25+ Years Experience",
    "faculty.teacher3.name": "Qari Yusuf",
    "faculty.teacher3.title": "Quran Recitation Teacher",
    "faculty.teacher3.qual": "Qari | 8+ Years Experience",
    // Donation
    "donation.title": "Support Islamic Education",
    "donation.subtitle": "Support Islamic Education for a Better Future",
    "donation.text": "Your generous contribution helps us provide quality Islamic education to students who need it most. Every donation makes a difference.",
    "donation.button": "Donate Now",
    "donation.upi": "UPI ID",
    "donation.bank": "Bank Details",
    "donation.bank.name": "Bank Name: State Bank",
    "donation.bank.account": "Account: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "Your contribution helps us educate future generations.",
    // Footer
    "footer.contact": "Contact Us",
    "footer.phone": "Phone: +91 9876543210",
    "footer.email": "Email: info@alnoormadarsa.com",
    "footer.address": "123, Islamic Center Road, City, State - 400001",
    "footer.quicklinks": "Quick Links",
    "footer.copyright": "© 2026 Al-Noor Madarsa. All rights reserved.",
    "footer.followus": "Follow Us",
    // About Page
    "about.title": "About Al-Noor Madarsa",
    "about.history.title": "Our History",
    "about.history.text": "Al-Noor Madarsa was established in 1998 by Maulana Muhammad Ismail with a vision to provide quality Islamic education combined with moral values. Starting with just 15 students, the Madarsa has grown to serve over 500 students annually.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To provide comprehensive Islamic education rooted in the Quran and Sunnah, fostering knowledgeable, ethical, and responsible individuals who contribute positively to society.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "To become a leading institution of Islamic learning, producing scholars and leaders who uphold Islamic values while embracing modern knowledge.",
    "about.founder.title": "Founder's Message",
    "about.founder.text": "\"Education is the key to understanding our faith and serving humanity. At Al-Noor Madarsa, we strive to nurture not just the mind, but the soul of every student.\" — Maulana Muhammad Ismail",
    "about.achievements.title": "Our Achievements",
    "about.achievements.students": "500+ Students Educated",
    "about.achievements.graduates": "200+ Hafiz Graduated",
    "about.achievements.years": "25+ Years of Service",
    "about.achievements.scholars": "50+ Scholars Produced",
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We'd love to hear from you",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.info.title": "Contact Information",
  },
  ur: {
    "nav.home": "ہوم",
    "nav.about": "ہمارے بارے میں",
    "nav.courses": "کورسز",
    "nav.faculty": "اساتذہ",
    "nav.donation": "عطیات",
    "nav.contact": "رابطہ",
    "hero.welcome": "النور مدرسہ میں خوش آمدید",
    "hero.subtitle": "معیاری اسلامی اور اخلاقی تعلیم فراہم کرنا",
    "hero.apply": "ابھی درخواست دیں",
    "hero.donate": "ابھی عطیہ دیں",
    "about.preview.title": "ہمارے مدرسے کے بارے میں",
    "about.preview.text": "النور مدرسہ دو دہائیوں سے زائد عرصے سے اسلامی تعلیم کا مینار نور ہے، نوجوان ذہنوں کو قرآن و سنت کی روشنی سے منور کر رہا ہے۔",
    "about.preview.readmore": "مزید پڑھیں",
    "courses.title": "ہمارے کورسز",
    "courses.subtitle": "جامع اسلامی تعلیمی پروگرامز",
    "course.hifz.name": "حفظ القرآن",
    "course.hifz.desc": "تجوید کے مکمل قواعد کے ساتھ قرآن مجید کا مکمل حفظ",
    "course.hifz.duration": "مدت: 2-3 سال",
    "course.nazra.name": "ناظرہ قرآن",
    "course.nazra.desc": "صحیح تلفظ اور بنیادی تجوید کے ساتھ قرآن مجید روانی سے پڑھنا",
    "course.nazra.duration": "مدت: 6-12 ماہ",
    "course.alim.name": "عالم کورس",
    "course.alim.desc": "تفسیر، حدیث، فقہ اور عربی زبان پر مشتمل جامع اسلامی علوم",
    "course.alim.duration": "مدت: 6-8 سال",
    "faculty.title": "ہمارے اساتذہ",
    "faculty.subtitle": "تجربہ کار اور مخلص اساتذہ",
    "faculty.teacher1.name": "مولانا احمد",
    "faculty.teacher1.title": "شعبہ حفظ کے سربراہ",
    "faculty.teacher1.qual": "عالم | 15+ سال تجربہ",
    "faculty.teacher2.name": "مفتی عبداللہ",
    "faculty.teacher2.title": "سینئر اسلامی عالم",
    "faculty.teacher2.qual": "مفتی | 25+ سال تجربہ",
    "faculty.teacher3.name": "قاری یوسف",
    "faculty.teacher3.title": "قرآن تلاوت کے استاد",
    "faculty.teacher3.qual": "قاری | 8+ سال تجربہ",
    "donation.title": "اسلامی تعلیم کی حمایت کریں",
    "donation.subtitle": "بہتر مستقبل کے لیے اسلامی تعلیم کی حمایت کریں",
    "donation.text": "آپ کا سخاوتی عطیہ ان طلباء کو معیاری اسلامی تعلیم فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔",
    "donation.button": "ابھی عطیہ دیں",
    "donation.upi": "یو پی آئی آئی ڈی",
    "donation.bank": "بینک تفصیلات",
    "donation.bank.name": "بینک کا نام: اسٹیٹ بینک",
    "donation.bank.account": "اکاؤنٹ: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "آپ کا تعاون آنے والی نسلوں کی تعلیم میں مدد کرتا ہے۔",
    "footer.contact": "ہم سے رابطہ کریں",
    "footer.phone": "فون: +91 9876543210",
    "footer.email": "ای میل: info@alnoormadarsa.com",
    "footer.address": "123، اسلامی سینٹر روڈ، شہر، ریاست - 400001",
    "footer.quicklinks": "فوری لنکس",
    "footer.copyright": "© 2026 النور مدرسہ۔ جملہ حقوق محفوظ ہیں۔",
    "footer.followus": "ہمیں فالو کریں",
    "about.title": "النور مدرسہ کے بارے میں",
    "about.history.title": "ہماری تاریخ",
    "about.history.text": "النور مدرسہ 1998 میں مولانا محمد اسماعیل نے قائم کیا تھا۔ صرف 15 طلباء سے شروع ہو کر اب سالانہ 500 سے زائد طلباء کو تعلیم فراہم کر رہا ہے۔",
    "about.mission.title": "ہمارا مشن",
    "about.mission.text": "قرآن و سنت پر مبنی جامع اسلامی تعلیم فراہم کرنا، علم دوست، اخلاقی اور ذمہ دار افراد تیار کرنا۔",
    "about.vision.title": "ہمارا وژن",
    "about.vision.text": "اسلامی تعلیم کا ایک سرکردہ ادارہ بننا جو علماء اور رہنما تیار کرے۔",
    "about.founder.title": "بانی کا پیغام",
    "about.founder.text": "\"تعلیم ہمارے ایمان کو سمجھنے اور انسانیت کی خدمت کی کلید ہے۔\" — مولانا محمد اسماعیل",
    "about.achievements.title": "ہماری کامیابیاں",
    "about.achievements.students": "500+ طلباء کو تعلیم دی",
    "about.achievements.graduates": "200+ حافظ فارغ التحصیل",
    "about.achievements.years": "25+ سال خدمت",
    "about.achievements.scholars": "50+ علماء تیار کیے",
    "contact.title": "ہم سے رابطہ کریں",
    "contact.subtitle": "ہم آپ سے سننا چاہیں گے",
    "contact.form.name": "آپ کا نام",
    "contact.form.email": "آپ کا ای میل",
    "contact.form.message": "آپ کا پیغام",
    "contact.form.submit": "پیغام بھیجیں",
    "contact.info.title": "رابطے کی معلومات",
  },
  hi: {
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.courses": "कोर्स",
    "nav.faculty": "शिक्षक",
    "nav.donation": "दान",
    "nav.contact": "संपर्क",
    "hero.welcome": "अल-नूर मदरसे में आपका स्वागत है",
    "hero.subtitle": "गुणवत्तापूर्ण इस्लामी और नैतिक शिक्षा प्रदान करना",
    "hero.apply": "अभी आवेदन करें",
    "hero.donate": "अभी दान करें",
    "about.preview.title": "हमारे मदरसे के बारे में",
    "about.preview.text": "अल-नूर मदरसा दो दशकों से अधिक समय से इस्लामी शिक्षा का प्रकाश स्तंभ रहा है, युवा मनों को कुरान और सुन्नत के प्रकाश से प्रबुद्ध कर रहा है।",
    "about.preview.readmore": "और पढ़ें",
    "courses.title": "हमारे कोर्स",
    "courses.subtitle": "व्यापक इस्लामी शिक्षा कार्यक्रम",
    "course.hifz.name": "हिफ्ज़-उल-कुरान",
    "course.hifz.desc": "तजवीद के नियमों के साथ पवित्र कुरान का संपूर्ण याद करना।",
    "course.hifz.duration": "अवधि: 2-3 वर्ष",
    "course.nazra.name": "नाज़रा कुरान",
    "course.nazra.desc": "सही उच्चारण और बुनियादी तजवीद के साथ कुरान पढ़ना सीखना।",
    "course.nazra.duration": "अवधि: 6-12 महीने",
    "course.alim.name": "आलिम कोर्स",
    "course.alim.desc": "तफसीर, हदीस, फिक़्ह और अरबी भाषा को शामिल करने वाली व्यापक इस्लामी शिक्षा।",
    "course.alim.duration": "अवधि: 6-8 वर्ष",
    "faculty.title": "हमारे शिक्षक",
    "faculty.subtitle": "अनुभवी और समर्पित शिक्षक",
    "faculty.teacher1.name": "मौलाना अहमद",
    "faculty.teacher1.title": "हिफ्ज़ विभाग के प्रमुख",
    "faculty.teacher1.qual": "आलिम | 15+ वर्ष अनुभव",
    "faculty.teacher2.name": "मुफ्ती अब्दुल्लाह",
    "faculty.teacher2.title": "वरिष्ठ इस्लामी विद्वान",
    "faculty.teacher2.qual": "मुफ्ती | 25+ वर्ष अनुभव",
    "faculty.teacher3.name": "क़ारी यूसुफ",
    "faculty.teacher3.title": "कुरान तिलावत शिक्षक",
    "faculty.teacher3.qual": "क़ारी | 8+ वर्ष अनुभव",
    "donation.title": "इस्लामी शिक्षा का समर्थन करें",
    "donation.subtitle": "बेहतर भविष्य के लिए इस्लामी शिक्षा का समर्थन करें",
    "donation.text": "आपका उदार दान उन छात्रों को गुणवत्तापूर्ण इस्लामी शिक्षा प्रदान करने में मदद करता है जिन्हें इसकी सबसे अधिक आवश्यकता है।",
    "donation.button": "अभी दान करें",
    "donation.upi": "UPI आईडी",
    "donation.bank": "बैंक विवरण",
    "donation.bank.name": "बैंक का नाम: स्टेट बैंक",
    "donation.bank.account": "खाता: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "आपका योगदान आने वाली पीढ़ियों को शिक्षित करने में मदद करता है।",
    "footer.contact": "संपर्क करें",
    "footer.phone": "फोन: +91 9876543210",
    "footer.email": "ईमेल: info@alnoormadarsa.com",
    "footer.address": "123, इस्लामिक सेंटर रोड, शहर, राज्य - 400001",
    "footer.quicklinks": "त्वरित लिंक",
    "footer.copyright": "© 2026 अल-नूर मदरसा। सर्वाधिकार सुरक्षित।",
    "footer.followus": "हमें फॉलो करें",
    "about.title": "अल-नूर मदरसे के बारे में",
    "about.history.title": "हमारा इतिहास",
    "about.history.text": "अल-नूर मदरसा 1998 में मौलाना मुहम्मद इस्माइल द्वारा स्थापित किया गया था। केवल 15 छात्रों से शुरू होकर अब सालाना 500+ छात्रों को शिक्षा दे रहा है।",
    "about.mission.title": "हमारा मिशन",
    "about.mission.text": "कुरान और सुन्नत पर आधारित व्यापक इस्लामी शिक्षा प्रदान करना, ज्ञानी, नैतिक और जिम्मेदार व्यक्तियों का निर्माण करना।",
    "about.vision.title": "हमारा विज़न",
    "about.vision.text": "इस्लामी शिक्षा का एक अग्रणी संस्थान बनना जो विद्वानों और नेताओं का निर्माण करे।",
    "about.founder.title": "संस्थापक का संदेश",
    "about.founder.text": "\"शिक्षा हमारे विश्वास को समझने और मानवता की सेवा की कुंजी है।\" — मौलाना मुहम्मद इस्माइल",
    "about.achievements.title": "हमारी उपलब्धियां",
    "about.achievements.students": "500+ छात्रों को शिक्षित किया",
    "about.achievements.graduates": "200+ हाफ़िज़ स्नातक",
    "about.achievements.years": "25+ वर्षों की सेवा",
    "about.achievements.scholars": "50+ विद्वान तैयार किए",
    "contact.title": "संपर्क करें",
    "contact.subtitle": "हम आपसे सुनना चाहेंगे",
    "contact.form.name": "आपका नाम",
    "contact.form.email": "आपका ईमेल",
    "contact.form.message": "आपका संदेश",
    "contact.form.submit": "संदेश भेजें",
    "contact.info.title": "संपर्क जानकारी",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  const dir = lang === "ur" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      <div dir={dir} data-lang={lang}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
