import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ur" | "hi";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.courses": "Courses",
    "nav.faculty": "Faculty",
    "nav.donation": "Donation",
    "nav.contact": "Contact",
    // Hero
    "hero.welcome": "Welcome to Darul Uloom Junediya Ajmatia",
    "hero.subtitle": "Providing Quality Islamic & Modern Education since 2004 — Mehnd, Ghazipur, Uttar Pradesh",
    "hero.apply": "Apply Now",
    "hero.donate": "Donate Now",
    // About Preview
    "about.preview.title": "About Our Madarsa",
    "about.preview.text": "Darul Uloom Junediya Ajmatia was founded on 1 March 2004 by Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih (Sajjada Nashin), Dargah Shah Ajmal, Allahabad. Located in Junediya, Ghazipur near Dargah Shah Wali Qadri, we provide holistic education from Class 1 to 8 combining Islamic and modern subjects.",
    "about.preview.readmore": "Read More",
    // Courses
    "courses.title": "Our Courses",
    "courses.subtitle": "Comprehensive Islamic & Modern Education Programs",
    "course.hifz.name": "Hifz-ul-Quran",
    "course.hifz.desc": "Complete memorization of the Holy Quran with proper Tajweed rules and pronunciation.",
    "course.hifz.duration": "Duration: 2-3 Years",
    "course.nazra.name": "Nazra Quran",
    "course.nazra.desc": "Learning to read the Holy Quran fluently with correct pronunciation and basic Tajweed.",
    "course.nazra.duration": "Duration: 6-12 Months",
    "course.alim.name": "Class 1 to 8 (Hindi Medium)",
    "course.alim.desc": "Science, Math, English, Hindi, Urdu, Deeniyat and other subjects taught in Hindi medium following standard curriculum.",
    "course.alim.duration": "Duration: 8 Years",
    // Faculty
    "faculty.title": "Our Faculty",
    "faculty.subtitle": "Experienced and Dedicated Teachers",
    "faculty.teacher1.name": "Hafiz Tabrez (Jank)",
    "faculty.teacher1.title": "Principal",
    "faculty.teacher1.qual": "Subjects: Urdu, Deeniyat",
    "faculty.teacher2.name": "Hafiz Qari Jabir Hasan",
    "faculty.teacher2.title": "Teacher",
    "faculty.teacher2.qual": "Subjects: Urdu, Hindi",
    "faculty.teacher3.name": "Master Md. Nizamuddin",
    "faculty.teacher3.title": "Teacher",
    "faculty.teacher3.qual": "Subjects: Hindi, Math",
    // Donation
    "donation.title": "Support Islamic Education",
    "donation.subtitle": "Support Islamic Education for a Better Future",
    "donation.text": "Your generous contribution helps us provide quality Islamic and modern education to students who need it most. Every donation makes a difference.",
    "donation.button": "Donate Now",
    "donation.upi": "UPI ID",
    "donation.bank": "Bank Details",
    "donation.bank.name": "Bank Name: State Bank",
    "donation.bank.account": "Account: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "Your contribution helps us educate future generations.",
    // Footer
    "footer.contact": "Contact Us",
    "footer.phone": "Phone: +91 9876543210",
    "footer.email": "Email: info@darululoomajmatia.com",
    "footer.address": "Junediya, Ghazipur, near Dargah Shah Wali Qadri, Uttar Pradesh",
    "footer.quicklinks": "Quick Links",
    "footer.copyright": "© 2026 Darul Uloom Junediya Ajmatia. All rights reserved.",
    "footer.followus": "Follow Us",
    // About Page
    "about.title": "About Darul Uloom Junediya Ajmatia",
    "about.history.title": "Our History",
    "about.history.text": "Darul Uloom Junediya Ajmatia was established on 1 March 2004 by Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih (Sajjada Nashin of Dargah Shah Ajmal, Allahabad). Located in Mehnd, Ghazipur, Uttar Pradesh near Dargah Shah Wali Qadri, the institution has grown into a centre of excellence offering both Islamic and modern education from Class 1 to 8.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To provide comprehensive education combining Islamic values with modern subjects, nurturing disciplined, knowledgeable and morally upright individuals who contribute positively to society.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "To become a leading institution of Islamic and modern learning in Uttar Pradesh, producing scholars and responsible citizens who uphold Islamic values while embracing contemporary knowledge.",
    "about.founder.title": "Founder's Message",
    "about.founder.text": "\"Education is the light that dispels the darkness of ignorance. At Darul Uloom Junediya Ajmatia, we strive to nurture not just the mind, but the soul and character of every student.\" — Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih",
    "about.achievements.title": "Our Achievements",
    "about.achievements.students": "500+ Students Educated",
    "about.achievements.graduates": "200+ Hafiz Graduated",
    "about.achievements.years": "20+ Years of Service",
    "about.achievements.scholars": "14 Rooms & 3 Halls",
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We'd love to hear from you",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.enquiry": "Select Inquiry Type",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.info.title": "Contact Information",
    // About page extra
    "about.est": "Established: 1 March 2004",
    "about.whoweare": "Who We Are",
    "about.ourstory": "Our Story",
    "about.milestones": "Milestones",
    "about.ourjourney": "Our Journey",
    "about.purpose": "Purpose",
    "about.missionvision": "Mission & Vision",
    "about.whatdrivesus": "What Drives Us",
    "about.corevalues": "Core Values",
    "about.wordswisdom": "Words of Wisdom",
    "about.joincommunity": "Join Our Community",
    "about.jointext": "Become part of our educational journey. Apply today or support our mission through donation.",
    "about.sendmessage": "Send Message",
    // Timeline
    "timeline.2004": "Darul Uloom Junediya Ajmatia was founded on 1 March 2004 by Hazrat Syed Akmal Ahmad Ajmali Rahmatullah Alaih.",
    "timeline.2006": "The first student batch completed foundational studies as admissions steadily increased with community support.",
    "timeline.2010": "Campus expansion added 14 rooms, 3 halls, an office, and a library to support growing academic needs.",
    "timeline.2015": "The curriculum expanded from Class 1 to 8, including Science, Math, English, Hindi, Urdu, and Deeniyat.",
    "timeline.2024": "The institution crossed 500+ students with a dedicated team of 7 teachers.",
    // Values
    "value.knowledge.title": "Authentic Knowledge",
    "value.knowledge.desc": "Every lesson is rooted in reliable Islamic knowledge from the Quran and Sunnah.",
    "value.teaching.title": "Compassionate Teaching",
    "value.teaching.desc": "Our teachers mentor each student with patience, care, and personal attention.",
    "value.service.title": "Service to Community",
    "value.service.desc": "We support the local community through outreach, events, and accessible education.",
    "value.excellence.title": "Excellence",
    "value.excellence.desc": "We uphold high standards in both Islamic studies and modern education.",
    // Faculty page
    "faculty.ourteam": "Our Team",
    "faculty.experienced": "Dedicated & Experienced",
    "faculty.manager.title": "Manager",
    "faculty.manager.qual": "Head Office",
    "faculty.principal.title": "Principal",
    "faculty.viceprincipal.title": "Vice Principal",
    "faculty.principal.qual": "Subjects: Urdu, Deeniyat",
    "faculty.teacher.title": "Teacher",
    "faculty.member.manager": "Syed Jan Hasan Ajmali",
    "faculty.member.tabrez": "Hafiz Tabrez (Jank)",
    "faculty.member.jabir": "Hafiz Qari Jabir Hasan",
    "faculty.member.usman": "Hafiz Qari Usman Khan",
    "faculty.member.abdullah": "Hafiz Abdullah Khan",
    "faculty.member.nizam": "Master Md. Nizamuddin",
    "faculty.member.jamshed": "Master Jamshed Khan",
    "faculty.member.pawan": "Master Pawan Ahmad",
    "faculty.jabir.qual": "Subjects: Urdu, Hindi",
    "faculty.usman.qual": "Subjects: Urdu, Hindi",
    "faculty.abdullah.qual": "Subjects: Arabic",
    "faculty.nizamuddin.qual": "Subjects: Hindi, Math",
    "faculty.jamshed.qual": "Subjects: Math, General Knowledge",
    "faculty.pawan.qual": "Subjects: English, Social Science",
    "home.leadership.badge": "Leadership Team",
    "home.leadership.heading": "Management & Leadership",
    "home.leadership.subheading": "Founder, Manager and Principal",
    "home.leadership.viewFaculty": "View Full Faculty",
    // Home page labels/news
    "home.news.pinned": "Pinned",
    "home.news.event": "Event",
    "home.news.notice": "Notice",
    "home.news.latest": "Latest Updates",
    "home.news.heading": "Announcements & News",
    "home.news.subheading": "Stay updated with the latest from Darul Uloom Junediya Ajmatia",
    "home.news.admission.title": "New Admissions Open for 2026-27 Academic Year",
    "home.news.admission.desc": "Darul Uloom Junediya Ajmatia is now accepting applications for Hifz, Nazra and Class 1-8. Limited seats, apply early.",
    "home.news.quran.title": "Annual Quran Recitation Competition",
    "home.news.quran.desc": "Join our yearly Quran recitation event open to all students and community members.",
    "home.news.eid.title": "Eid Holiday Schedule",
    "home.news.eid.desc": "Madarsa closed April 18-22 for Eid. Classes resume April 23.",
    // Courses page
    "courses.whatweoffer": "What We Offer",
    "courses.readytojoin": "Ready to Begin Your Journey?",
    "courses.enrolltext": "Enroll today and take the first step towards comprehensive Islamic education.",
    // Contact & Donation
    "contact.sendmessage": "Send a Message",
    "contact.getintouch": "Get In Touch",
    "contact.location": "Junediya, Ghazipur",
    "contact.locationdesc": "Near Dargah Shah Wali Qadri, Uttar Pradesh",
    "donation.supportus": "Support Us",
    "donation.howtodonate": "How to Donate",
    "donation.jazakallah": "JazakAllah Khair - your generous contribution helps us provide quality education to students who need it most.",
    "donation.scantext": "Scan or copy UPI ID to donate instantly",
  },
  ur: {
    "nav.home": "ہوم",
    "nav.about": "ہمارے بارے میں",
    "nav.courses": "کورسز",
    "nav.faculty": "اساتذہ",
    "nav.donation": "عطیات",
    "nav.contact": "رابطہ",
    "hero.welcome": "النور مدرسہ میں خوش آمدید",
    "hero.subtitle": "معیاری اسلامی اور اخلاقی تعلیم فراہم کرنا",
    "hero.apply": "ابھی درخواست دیں",
    "hero.donate": "ابھی عطیہ دیں",
    "about.preview.title": "ہمارے مدرسے کے بارے میں",
    "about.preview.text": "دارالعلوم جنیدیہ اجماتیہ کی بنیاد 1 مارچ 2004 کو حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ نے رکھی۔ یہ ادارہ جنیدیہ، غازی پور میں درگاہ شاہ ولی قادری کے قریب واقع ہے اور جماعت 1 تا 8 تک اسلامی اور عصری تعلیم فراہم کرتا ہے۔",
    "about.preview.readmore": "مزید پڑھیں",
    "courses.title": "ہمارے کورسز",
    "courses.subtitle": "جامع اسلامی تعلیمی پروگرامز",
    "course.hifz.name": "حفظ القرآن",
    "course.hifz.desc": "تجوید کے مکمل قواعد کے ساتھ قرآن مجید کا مکمل حفظ",
    "course.hifz.duration": "مدت: 2-3 سال",
    "course.nazra.name": "ناظرہ قرآن",
    "course.nazra.desc": "صحیح تلفظ اور بنیادی تجوید کے ساتھ قرآن مجید روانی سے پڑھنا",
    "course.nazra.duration": "مدت: 6-12 ماہ",
    "course.alim.name": "عالم کورس",
    "course.alim.desc": "تفسیر، حدیث، فقہ اور عربی زبان پر مشتمل جامع اسلامی علوم",
    "course.alim.duration": "مدت: 6-8 سال",
    "faculty.title": "ہمارے اساتذہ",
    "faculty.subtitle": "تجربہ کار اور مخلص اساتذہ",
    "faculty.teacher1.name": "مولانا احمد",
    "faculty.teacher1.title": "شعبہ حفظ کے سربراہ",
    "faculty.teacher1.qual": "عالم | 15+ سال تجربہ",
    "faculty.teacher2.name": "مفتی عبداللہ",
    "faculty.teacher2.title": "سینئر اسلامی عالم",
    "faculty.teacher2.qual": "مفتی | 25+ سال تجربہ",
    "faculty.teacher3.name": "قاری یوسف",
    "faculty.teacher3.title": "قرآن تلاوت کے استاد",
    "faculty.teacher3.qual": "قاری | 8+ سال تجربہ",
    "donation.title": "اسلامی تعلیم کی حمایت کریں",
    "donation.subtitle": "بہتر مستقبل کے لیے اسلامی تعلیم کی حمایت کریں",
    "donation.text": "آپ کا سخاوتی عطیہ ان طلباء کو معیاری اسلامی تعلیم فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔",
    "donation.button": "ابھی عطیہ دیں",
    "donation.upi": "یو پی آئی آئی ڈی",
    "donation.bank": "بینک تفصیلات",
    "donation.bank.name": "بینک کا نام: اسٹیٹ بینک",
    "donation.bank.account": "اکاؤنٹ: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "آپ کا تعاون آنے والی نسلوں کی تعلیم میں مدد کرتا ہے۔",
    "footer.contact": "ہم سے رابطہ کریں",
    "footer.phone": "فون: +91 9876543210",
    "footer.email": "ای میل: info@darululoomajmatia.com",
    "footer.address": "جنیدیہ، غازی پور، درگاہ شاہ ولی قادری کے قریب، اتر پردیش",
    "footer.quicklinks": "فوری لنکس",
    "footer.copyright": "© 2026 دارالعلوم جنیدیہ اجماتیہ۔ جملہ حقوق محفوظ ہیں۔",
    "footer.followus": "ہمیں فالو کریں",
    "about.title": "دارالعلوم جنیدیہ اجماتیہ کے بارے میں",
    "about.history.title": "ہماری تاریخ",
    "about.history.text": "دارالعلوم جنیدیہ اجماتیہ 1 مارچ 2004 کو حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ (سجادہ نشین، درگاہ شاہ اجمل، الہ آباد) نے قائم کیا۔ یہ ادارہ غازی پور کے علاقہ مَہند میں واقع ہے اور جماعت 1 تا 8 تک اسلامی اور جدید تعلیم فراہم کرتا ہے۔",
    "about.mission.title": "ہمارا مشن",
    "about.mission.text": "قرآن و سنت پر مبنی جامع اسلامی تعلیم فراہم کرنا، علم دوست، اخلاقی اور ذمہ دار افراد تیار کرنا۔",
    "about.vision.title": "ہمارا وژن",
    "about.vision.text": "اسلامی تعلیم کا ایک سرکردہ ادارہ بننا جو علماء اور رہنما تیار کرے۔",
    "about.founder.title": "بانی کا پیغام",
    "about.founder.text": "\"تعلیم جہالت کی تاریکی کو دور کرنے والی روشنی ہے۔ دارالعلوم جنیدیہ اجماتیہ میں ہم ہر طالب علم کے ذہن کے ساتھ اس کے کردار اور روح کی بھی تربیت کرتے ہیں۔\" — حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ",
    "about.achievements.title": "ہماری کامیابیاں",
    "about.achievements.students": "500+ طلباء کو تعلیم دی",
    "about.achievements.graduates": "200+ حافظ فارغ التحصیل",
    "about.achievements.years": "20+ سال خدمت",
    "about.achievements.scholars": "14 کمرے اور 3 بڑے ہال",
    "contact.title": "ہم سے رابطہ کریں",
    "contact.subtitle": "ہم آپ سے سننا چاہیں گے",
    "contact.form.name": "آپ کا نام",
    "contact.form.email": "آپ کا ای میل",
    "contact.form.enquiry": "استفسار کی قسم منتخب کریں",
    "contact.form.message": "آپ کا پیغام",
    "contact.form.submit": "پیغام بھیجیں",
    "contact.info.title": "رابطے کی معلومات",
    // About page extra
    "about.est": "قیام: 1 مارچ 2004",
    "about.whoweare": "ہمارے بارے میں",
    "about.ourstory": "ہماری کہانی",
    "about.milestones": "سنگ میل",
    "about.ourjourney": "ہمارا سفر",
    "about.purpose": "مقصد",
    "about.missionvision": "مشن اور وژن",
    "about.whatdrivesus": "ہماری اقدار",
    "about.corevalues": "بنیادی اقدار",
    "about.wordswisdom": "حکمت کے الفاظ",
    "about.joincommunity": "ہماری برادری میں شامل ہوں",
    "about.jointext": "اسلامی تعلیم کی میراث کا حصہ بنیں۔ آج ہی درخواست دیں یا عطیہ دے کر ہمارے مشن کی حمایت کریں۔",
    "about.sendmessage": "پیغام بھیجیں",
    // Timeline
    "timeline.2004": "دارالعلوم جنیدیہ اجماتیہ کا قیام 1 مارچ 2004 کو حضرت سید اکمل احمد اجمالی رحمۃ اللہ علیہ نے کیا۔",
    "timeline.2006": "طلباء کا پہلا بیچ ابتدائی تعلیم مکمل کر کے فارغ ہوا۔ کمیونٹی کی حمایت سے داخلے بڑھتے رہے۔",
    "timeline.2010": "نئی عمارت تعمیر ہوئی — 14 کمرے، 3 بڑے ہال، 1 دفتر اور 1 لائبریری کا اضافہ ہوا۔",
    "timeline.2015": "نصاب کو کلاس 1 تا 8 تک وسعت دی گئی جس میں سائنس، ریاضی، انگریزی، ہندی، اردو اور دینیات شامل ہیں۔",
    "timeline.2024": "500+ طلباء کا سنگ میل عبور کیا اور 7 قابل اساتذہ کی ٹیم مکمل ہوئی۔",
    // Values
    "value.knowledge.title": "مستند علم",
    "value.knowledge.desc": "قرآن و سنت پر مبنی، ہر سبق مستند اسلامی علم پر قائم ہے۔",
    "value.teaching.title": "شفقت آمیز تعلیم",
    "value.teaching.desc": "ہمارے اساتذہ ہر طالب علم کی صبر، محبت اور انفرادی توجہ سے تربیت کرتے ہیں۔",
    "value.service.title": "خدمت خلق",
    "value.service.desc": "ہم آؤٹ ریچ، تقریبات اور مفت تعلیمی پروگراموں کے ذریعے کمیونٹی کی خدمت کرتے ہیں۔",
    "value.excellence.title": "عمدگی",
    "value.excellence.desc": "ہم اسلامی اور اخلاقی تعلیم دونوں میں اعلیٰ ترین معیار قائم رکھتے ہیں۔",
    // Faculty page
    "faculty.ourteam": "ہماری ٹیم",
    "faculty.experienced": "تجربہ کار اور مخلص",
    "faculty.manager.title": "مہتمم (منیجر)",
    "faculty.manager.qual": "ہیڈ آفس",
    "faculty.principal.title": "پرنسپل",
    "faculty.viceprincipal.title": "نائب پرنسپل",
    "faculty.principal.qual": "مضامین: اردو، دینیات",
    "faculty.teacher.title": "استاد",
    "faculty.member.manager": "سید جان حسن اجمالی",
    "faculty.member.tabrez": "حافظ تبریز (جانک)",
    "faculty.member.jabir": "حافظ قاری جابر حسن",
    "faculty.member.usman": "حافظ قاری عثمان خان",
    "faculty.member.abdullah": "حافظ عبداللہ خان",
    "faculty.member.nizam": "ماسٹر محمد نظام الدین",
    "faculty.member.jamshed": "ماسٹر جمشید خان",
    "faculty.member.pawan": "ماسٹر پون احمد",
    "faculty.jabir.qual": "مضامین: اردو، ہندی",
    "faculty.usman.qual": "مضامین: اردو، ہندی",
    "faculty.abdullah.qual": "مضامین: عربی",
    "faculty.nizamuddin.qual": "مضامین: ہندی، ریاضی",
    "faculty.jamshed.qual": "مضامین: ریاضی، جنرل نالج",
    "faculty.pawan.qual": "مضامین: انگریزی، سماجی علوم",
    "home.leadership.badge": "انتظامی ٹیم",
    "home.leadership.heading": "انتظامیہ اور قیادت",
    "home.leadership.subheading": "بانی، منیجر اور پرنسپل",
    "home.leadership.viewFaculty": "تمام اساتذہ دیکھیں",
    // Courses page
    "courses.whatweoffer": "ہم کیا پیش کرتے ہیں",
    "courses.readytojoin": "اپنا سفر شروع کرنے کے لیے تیار ہیں؟",
    "courses.enrolltext": "آج ہی داخلہ لیں اور جامع اسلامی تعلیم کی طرف پہلا قدم اٹھائیں۔",
    // Contact & Donation
    "contact.sendmessage": "پیغام بھیجیں",
    "contact.getintouch": "رابطہ کریں",
    "contact.location": "جنیدیہ، غازی پور",
    "contact.locationdesc": "درگاہ شاہ ولی قادری کے قریب، اتر پردیش",
    "donation.supportus": "ہماری مدد کریں",
    "donation.howtodonate": "عطیہ کیسے دیں",
    "donation.jazakallah": "جزاک اللہ خیر — آپ کا سخاوتی عطیہ ان طلباء کو معیاری تعلیم فراہم کرنے میں مدد کرتا ہے جنہیں اس کی سب سے زیادہ ضرورت ہے۔",
    "donation.scantext": "فوری عطیہ کے لیے UPI ID اسکین یا کاپی کریں",
  },
  hi: {
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.courses": "कोर्स",
    "nav.faculty": "शिक्षक",
    "nav.donation": "दान",
    "nav.contact": "संपर्क",
    "hero.welcome": "दारुल उलूम जुनैदिया अजमतिया में आपका स्वागत है",
    "hero.subtitle": "सन् 2004 से गुणवत्तापूर्ण इस्लामी और आधुनिक शिक्षा - महंद, गाजीपुर, उत्तर प्रदेश",
    "hero.apply": "अभी आवेदन करें",
    "hero.donate": "अभी दान करें",
    "about.preview.title": "हमारे मदरसे के बारे में",
    "about.preview.text": "दारुल उलूम जुनैदिया अजमतिया की स्थापना 1 मार्च 2004 को हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह ने की। यह संस्थान जुनैदिया, गाजीपुर में दरगाह शाह वली कादरी के पास स्थित है और कक्षा 1 से 8 तक इस्लामी व आधुनिक शिक्षा प्रदान करता है।",
    "about.preview.readmore": "और पढ़ें",
    "courses.title": "हमारे कोर्स",
    "courses.subtitle": "व्यापक इस्लामी शिक्षा कार्यक्रम",
    "course.hifz.name": "हिफ्ज़-उल-कुरान",
    "course.hifz.desc": "तजवीद के नियमों के साथ पवित्र कुरान का संपूर्ण याद करना।",
    "course.hifz.duration": "अवधि: 2-3 वर्ष",
    "course.nazra.name": "नाज़रा कुरान",
    "course.nazra.desc": "सही उच्चारण और बुनियादी तजवीद के साथ कुरान पढ़ना सीखना।",
    "course.nazra.duration": "अवधि: 6-12 महीने",
    "course.alim.name": "आलिम कोर्स",
    "course.alim.desc": "तफसीर, हदीस, फिक़्ह और अरबी भाषा को शामिल करने वाली व्यापक इस्लामी शिक्षा।",
    "course.alim.duration": "अवधि: 6-8 वर्ष",
    "faculty.title": "हमारे शिक्षक",
    "faculty.subtitle": "अनुभवी और समर्पित शिक्षक",
    "faculty.teacher1.name": "मौलाना अहमद",
    "faculty.teacher1.title": "हिफ्ज़ विभाग के प्रमुख",
    "faculty.teacher1.qual": "आलिम | 15+ वर्ष अनुभव",
    "faculty.teacher2.name": "मुफ्ती अब्दुल्लाह",
    "faculty.teacher2.title": "वरिष्ठ इस्लामी विद्वान",
    "faculty.teacher2.qual": "मुफ्ती | 25+ वर्ष अनुभव",
    "faculty.teacher3.name": "क़ारी यूसुफ",
    "faculty.teacher3.title": "कुरान तिलावत शिक्षक",
    "faculty.teacher3.qual": "क़ारी | 8+ वर्ष अनुभव",
    "donation.title": "इस्लामी शिक्षा का समर्थन करें",
    "donation.subtitle": "बेहतर भविष्य के लिए इस्लामी शिक्षा का समर्थन करें",
    "donation.text": "आपका उदार दान उन छात्रों को गुणवत्तापूर्ण इस्लामी शिक्षा प्रदान करने में मदद करता है जिन्हें इसकी सबसे अधिक आवश्यकता है।",
    "donation.button": "अभी दान करें",
    "donation.upi": "UPI आईडी",
    "donation.bank": "बैंक विवरण",
    "donation.bank.name": "बैंक का नाम: स्टेट बैंक",
    "donation.bank.account": "खाता: 1234567890",
    "donation.bank.ifsc": "IFSC: SBIN0001234",
    "donation.message": "आपका योगदान आने वाली पीढ़ियों को शिक्षित करने में मदद करता है।",
    "footer.contact": "संपर्क करें",
    "footer.phone": "फोन: +91 9876543210",
    "footer.email": "ईमेल: info@darululoomajmatia.com",
    "footer.address": "जुनैदिया, गाजीपुर, दरगाह शाह वली कादरी के पास, उत्तर प्रदेश",
    "footer.quicklinks": "त्वरित लिंक",
    "footer.copyright": "© 2026 दारुल उलूम जुनैदिया अजमतिया। सर्वाधिकार सुरक्षित।",
    "footer.followus": "हमें फॉलो करें",
    "about.title": "दारुल उलूम जुनैदिया अजमतिया के बारे में",
    "about.history.title": "हमारा इतिहास",
    "about.history.text": "दारुल उलूम जुनैदिया अजमतिया की स्थापना 1 मार्च 2004 को हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह (सज्जादा नशीन, दरगाह शाह अजमल, इलाहाबाद) ने की। यह संस्थान महंद, गाजीपुर में स्थित है और कक्षा 1 से 8 तक इस्लामी व आधुनिक शिक्षा देता है।",
    "about.mission.title": "हमारा मिशन",
    "about.mission.text": "कुरान और सुन्नत पर आधारित व्यापक इस्लामी शिक्षा प्रदान करना, ज्ञानी, नैतिक और जिम्मेदार व्यक्तियों का निर्माण करना।",
    "about.vision.title": "हमारा विज़न",
    "about.vision.text": "इस्लामी शिक्षा का एक अग्रणी संस्थान बनना जो विद्वानों और नेताओं का निर्माण करे।",
    "about.founder.title": "संस्थापक का संदेश",
    "about.founder.text": "\"शिक्षा अज्ञानता के अंधकार को दूर करने वाली रोशनी है। दारुल उलूम जुनैदिया अजमतिया में हम हर छात्र के मन के साथ उसके चरित्र और आत्मा का भी विकास करते हैं।\" — हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह",
    "about.achievements.title": "हमारी उपलब्धियां",
    "about.achievements.students": "500+ छात्रों को शिक्षित किया",
    "about.achievements.graduates": "200+ हाफ़िज़ स्नातक",
    "about.achievements.years": "20+ वर्षों की सेवा",
    "about.achievements.scholars": "14 कमरे और 3 बड़े हॉल",
    "contact.title": "संपर्क करें",
    "contact.subtitle": "हम आपसे सुनना चाहेंगे",
    "contact.form.name": "आपका नाम",
    "contact.form.email": "आपका ईमेल",
    "contact.form.enquiry": "पूछताछ का प्रकार चुनें",
    "contact.form.message": "आपका संदेश",
    "contact.form.submit": "संदेश भेजें",
    "contact.info.title": "संपर्क जानकारी",
    // About page extra
    "about.est": "स्थापना: 1 मार्च 2004",
    "about.whoweare": "हम कौन हैं",
    "about.ourstory": "हमारी कहानी",
    "about.milestones": "मुख्य पड़ाव",
    "about.ourjourney": "हमारी यात्रा",
    "about.purpose": "उद्देश्य",
    "about.missionvision": "मिशन और विज़न",
    "about.whatdrivesus": "हमारी प्रेरणा",
    "about.corevalues": "मुख्य मूल्य",
    "about.wordswisdom": "प्रेरक विचार",
    "about.joincommunity": "हमारे समुदाय से जुड़ें",
    "about.jointext": "हमारी शैक्षिक यात्रा का हिस्सा बनें। आज आवेदन करें या दान देकर हमारे मिशन का समर्थन करें।",
    "about.sendmessage": "संदेश भेजें",
    // Timeline
    "timeline.2004": "दारुल उलूम जुनैदिया अजमतिया की स्थापना 1 मार्च 2004 को हज़रत सैयद अकमल अहमद अजमली रहमतुल्लाह अलैह ने की।",
    "timeline.2006": "पहले बैच ने बुनियादी शिक्षा पूरी की और समुदाय के समर्थन से दाखिले बढ़ते गए।",
    "timeline.2010": "कैम्पस विस्तार में 14 कमरे, 3 हॉल, एक कार्यालय और एक पुस्तकालय जोड़ा गया।",
    "timeline.2015": "पाठ्यक्रम कक्षा 1 से 8 तक बढ़ाया गया, जिसमें विज्ञान, गणित, अंग्रेज़ी, हिंदी, उर्दू और दीनियात शामिल हैं।",
    "timeline.2024": "संस्थान 500+ छात्रों के मील के पत्थर तक पहुंचा और 7 शिक्षकों की समर्पित टीम तैयार हुई।",
    // Values
    "value.knowledge.title": "प्रामाणिक ज्ञान",
    "value.knowledge.desc": "हर पाठ कुरान और सुन्नत पर आधारित विश्वसनीय इस्लामी ज्ञान पर टिका है।",
    "value.teaching.title": "सहानुभूतिपूर्ण शिक्षण",
    "value.teaching.desc": "हमारे शिक्षक हर छात्र का धैर्य, देखभाल और व्यक्तिगत ध्यान से मार्गदर्शन करते हैं।",
    "value.service.title": "समाज सेवा",
    "value.service.desc": "हम आउटरीच, कार्यक्रमों और सुलभ शिक्षा के माध्यम से समुदाय की सेवा करते हैं।",
    "value.excellence.title": "श्रेष्ठता",
    "value.excellence.desc": "हम इस्लामी और आधुनिक शिक्षा दोनों में उच्च मानक बनाए रखते हैं।",
    // Faculty page
    "faculty.ourteam": "हमारी टीम",
    "faculty.experienced": "समर्पित और अनुभवी",
    "faculty.manager.title": "प्रबंधक",
    "faculty.manager.qual": "हेड ऑफिस",
    "faculty.principal.title": "प्रधानाचार्य",
    "faculty.viceprincipal.title": "उप प्रधानाचार्य",
    "faculty.principal.qual": "विषय: उर्दू, दीनियात",
    "faculty.teacher.title": "शिक्षक",
    "faculty.member.manager": "सैयद जान हसन अजमली",
    "faculty.member.tabrez": "हाफ़िज़ तबरेज़ (जंक)",
    "faculty.member.jabir": "हाफ़िज़ क़ारी जाबिर हसन",
    "faculty.member.usman": "हाफ़िज़ क़ारी उस्मान खान",
    "faculty.member.abdullah": "हाफ़िज़ अब्दुल्लाह खान",
    "faculty.member.nizam": "मास्टर मोहम्मद निज़ामुद्दीन",
    "faculty.member.jamshed": "मास्टर जमशेद खान",
    "faculty.member.pawan": "मास्टर पवन अहमद",
    "faculty.jabir.qual": "विषय: उर्दू, हिंदी",
    "faculty.usman.qual": "विषय: उर्दू, हिंदी",
    "faculty.abdullah.qual": "विषय: अरबी",
    "faculty.nizamuddin.qual": "विषय: हिंदी, गणित",
    "faculty.jamshed.qual": "विषय: गणित, सामान्य ज्ञान",
    "faculty.pawan.qual": "विषय: अंग्रेज़ी, सामाजिक विज्ञान",
    "home.leadership.badge": "नेतृत्व टीम",
    "home.leadership.heading": "प्रबंधन और नेतृत्व",
    "home.leadership.subheading": "संस्थापक, प्रबंधक और प्रधानाचार्य",
    "home.leadership.viewFaculty": "पूरा शिक्षक समूह देखें",
    // Home page labels/news
    "home.news.pinned": "पिन किया गया",
    "home.news.event": "कार्यक्रम",
    "home.news.notice": "सूचना",
    "home.news.latest": "नवीनतम अपडेट",
    "home.news.heading": "घोषणाएं और समाचार",
    "home.news.subheading": "दारुल उलूम जुनैदिया अजमतिया की ताज़ा जानकारी देखें",
    "home.news.admission.title": "2026-27 शैक्षणिक सत्र के लिए नए प्रवेश शुरू",
    "home.news.admission.desc": "दारुल उलूम जुनैदिया अजमतिया में हिफ्ज़, नाज़रा और कक्षा 1-8 के लिए आवेदन खुले हैं। सीटें सीमित हैं, जल्दी आवेदन करें।",
    "home.news.quran.title": "वार्षिक कुरान तिलावत प्रतियोगिता",
    "home.news.quran.desc": "सभी छात्रों और समुदाय के लिए आयोजित वार्षिक कुरान तिलावत कार्यक्रम में शामिल हों।",
    "home.news.eid.title": "ईद अवकाश समय-सारणी",
    "home.news.eid.desc": "मदरसा 18-22 अप्रैल तक ईद अवकाश के कारण बंद रहेगा। कक्षाएं 23 अप्रैल से शुरू होंगी।",
    // Courses page
    "courses.whatweoffer": "हम क्या प्रदान करते हैं",
    "courses.readytojoin": "क्या आप अपनी यात्रा शुरू करने के लिए तैयार हैं?",
    "courses.enrolltext": "आज ही प्रवेश लें और व्यापक इस्लामी शिक्षा की ओर पहला कदम बढ़ाएं।",
    // Contact & Donation
    "contact.sendmessage": "संदेश भेजें",
    "contact.getintouch": "संपर्क करें",
    "contact.location": "जुनैदिया, गाजीपुर",
    "contact.locationdesc": "दरगाह शाह वली कादरी के पास, उत्तर प्रदेश",
    "donation.supportus": "हमारी सहायता करें",
    "donation.howtodonate": "दान कैसे करें",
    "donation.jazakallah": "जज़ाकल्लाह खैर - आपका उदार दान जरूरतमंद छात्रों को गुणवत्तापूर्ण शिक्षा देने में हमारी मदद करता है।",
    "donation.scantext": "तुरंत दान के लिए UPI आईडी स्कैन या कॉपी करें",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  const dir = lang === "ur" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      <div dir={dir} data-lang={lang}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
